/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_menu;

import javax.swing.JOptionPane;

/**
 *
 * @author lab_services_student
 */
public class Calculation extends javax.swing.JFrame {

    /**
     * Creates new form Calculation
     */
    public Calculation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonCALCULATE = new javax.swing.JButton();
        ButtonCLEAR = new javax.swing.JButton();
        RadioButtonIncrease = new javax.swing.JRadioButton();
        TextFieldInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuFileExit = new javax.swing.JMenuItem();
        MenuEdit = new javax.swing.JMenu();
        MenuEditCalculate = new javax.swing.JMenuItem();
        MenuEditClear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonCALCULATE.setText("CALCULATE");
        ButtonCALCULATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCALCULATEActionPerformed(evt);
            }
        });

        ButtonCLEAR.setText("CLEAR");
        ButtonCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCLEARActionPerformed(evt);
            }
        });

        RadioButtonIncrease.setText("Increase");
        RadioButtonIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonIncreaseActionPerformed(evt);
            }
        });

        TextFieldInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldInputActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Amount:");

        MenuFile.setText("File");

        MenuFileExit.setText("Exit");
        MenuFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileExitActionPerformed(evt);
            }
        });
        MenuFile.add(MenuFileExit);

        jMenuBar1.add(MenuFile);

        MenuEdit.setText("Edit");

        MenuEditCalculate.setText("Calculate");
        MenuEditCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditCalculateActionPerformed(evt);
            }
        });
        MenuEdit.add(MenuEditCalculate);

        MenuEditClear.setText("Clear");
        MenuEditClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEditClearActionPerformed(evt);
            }
        });
        MenuEdit.add(MenuEditClear);

        jMenuBar1.add(MenuEdit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioButtonIncrease)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(TextFieldInput)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(ButtonCALCULATE, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonCLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(RadioButtonIncrease)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCALCULATE)
                    .addComponent(ButtonCLEAR))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileExitActionPerformed
       int dialogButton = JOptionPane.YES_NO_OPTION;
       int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to exit?","Warning",dialogButton);
       if (dialogResult == JOptionPane.YES_OPTION)
       {
           System.exit(0);
       }
    }//GEN-LAST:event_MenuFileExitActionPerformed

    private void MenuEditCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditCalculateActionPerformed
      calculate();
    }//GEN-LAST:event_MenuEditCalculateActionPerformed

    private void ButtonCALCULATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCALCULATEActionPerformed
    calculate();
    }//GEN-LAST:event_ButtonCALCULATEActionPerformed

    private void RadioButtonIncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonIncreaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonIncreaseActionPerformed

    private void TextFieldInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldInputActionPerformed

    private void MenuEditClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEditClearActionPerformed
     clear();
    }//GEN-LAST:event_MenuEditClearActionPerformed

    private void ButtonCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCLEARActionPerformed
       clear();
    }//GEN-LAST:event_ButtonCLEARActionPerformed

    private void calculate()
    {
        try
        {
            double Amount = Double.parseDouble(this.TextFieldInput.getText());
            if (this.RadioButtonIncrease.isSelected())
            {
                Amount += Amount * 15/100;
                this.TextFieldInput.setText("" + Amount);
            }
            else
            {
                 this.TextFieldInput.setText("" + Amount);
            }
        }
        catch (NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Please enter valid number");
        }
        catch (Exception ex)
        {
             JOptionPane.showMessageDialog(null, "This error has occured: " + ex.toString());
        }
    }
    
    private void clear()
    {
        this.TextFieldInput.setText("");
        this.RadioButtonIncrease.setSelected(false);
    }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCALCULATE;
    private javax.swing.JButton ButtonCLEAR;
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JMenuItem MenuEditCalculate;
    private javax.swing.JMenuItem MenuEditClear;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenuItem MenuFileExit;
    private javax.swing.JRadioButton RadioButtonIncrease;
    private javax.swing.JTextField TextFieldInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
