/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_product_form;

import javax.swing.JOptionPane;

/**
 *
 * @author lab_services_student
 */
public class NewJFrameProductForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameProductForm
     */
    public NewJFrameProductForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextFieldNAME = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextFieldPRICE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        RadioButtonYES = new javax.swing.JRadioButton();
        RadioButtonNO = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        CheckBox = new javax.swing.JCheckBox();
        ProcessButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PRODUCTS FORM");

        jLabel2.setText("PRODUCT ID:");

        jLabel3.setText("PRODUCT NAME:");

        TextFieldNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNAMEActionPerformed(evt);
            }
        });

        jLabel4.setText("PRODUCT PRICE:");

        TextFieldPRICE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPRICEActionPerformed(evt);
            }
        });

        jLabel5.setText("DISCOUNT:");

        buttonGroup1.add(RadioButtonYES);
        RadioButtonYES.setText("YES");
        RadioButtonYES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonYESActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioButtonNO);
        RadioButtonNO.setText("NO");

        jLabel6.setText("INSURANCE:");

        ProcessButton.setText("PROCESS");
        ProcessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("CLEAR");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        ExitButton.setText("EXIT");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ProcessButton)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldID)
                            .addComponent(TextFieldNAME)
                            .addComponent(TextFieldPRICE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioButtonNO)
                                    .addComponent(RadioButtonYES)
                                    .addComponent(CheckBox))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(ClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextFieldNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextFieldPRICE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RadioButtonYES))
                .addGap(18, 18, 18)
                .addComponent(RadioButtonNO)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CheckBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProcessButton)
                    .addComponent(ClearButton)
                    .addComponent(ExitButton))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNAMEActionPerformed

    private void TextFieldPRICEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPRICEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPRICEActionPerformed

    private void RadioButtonYESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonYESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButtonYESActionPerformed

    private void ProcessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessButtonActionPerformed
      try
      {
          String ID;
          String Name;
          String Insurance;
          String Display;
          double Price = 0.0;
          double Discount = 0.0;
          boolean BooleanDiscount = false;
          ID = this.TextFieldID.getText();
          Name = this.TextFieldNAME.getText();
          Price = Double.parseDouble(this.TextFieldPRICE.getText());
          if (this.RadioButtonYES.isSelected())
          {
              Discount = Price * 10/100;
              BooleanDiscount = true;
          }
          if (this.RadioButtonNO.isSelected())
          {
               BooleanDiscount = true;
          }
          if (BooleanDiscount == false)
          {
              JOptionPane.showMessageDialog(null, "Please select a discount type.");
              return;
          }
          if (this.CheckBox.isSelected())
          {
              Insurance = "YES";
              Price += 100;
          }
          else
          {
              Insurance = "NO";
          }
          
          Display = "PRODUCT INVOICE\n" + "\n" + 
          "PRODUCT ID: " + ID + "\n" +
          "PRODUCT NAME: " + Name + "\n" +
          "PRODUCT PRICE: R " + Price + "\n" +
          "DISCOUNT AMOUNNT: R " + (Price - Discount) + "\n" +
          "INSURANCE: " + Insurance;
          JOptionPane.showMessageDialog(null, Display);
      }
      catch (Exception ex)
      {
          JOptionPane.showMessageDialog(null, ex.toString());
      }
    }//GEN-LAST:event_ProcessButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
    this.TextFieldID.setText("");
    this.TextFieldNAME.setText("");
    this.TextFieldPRICE.setText("");
    this.buttonGroup1.clearSelection();
    this.CheckBox.setSelected(false);
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
      int confirmed = JOptionPane.showConfirmDialog(null,
              "Are you sure you want to exit the program?",
              "Exit Program",
              JOptionPane.YES_NO_OPTION);
      
      if (confirmed == JOptionPane.YES_OPTION)
      {
          System.exit(0);
      }
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameProductForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ProcessButton;
    private javax.swing.JRadioButton RadioButtonNO;
    private javax.swing.JRadioButton RadioButtonYES;
    private javax.swing.JTextField TextFieldID;
    private javax.swing.JTextField TextFieldNAME;
    private javax.swing.JTextField TextFieldPRICE;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
